### ISSUE TITLE
เรื่อง token ครับ

### ISSUE THREAD

**Issue by playcodebyflapjack** [misterfocusth/LINE-ThaiPost-Tracking-Chatbot#1]
ผมเห็นในไฟล์ [server.js](https://github.com/misterfocusth/LINE-ThaiPost-Tracking-Chatbot/blob/main/server.js) มีการเก็บ channelAccessToken กับ channelSecret  fix code ไว้จะมีผลเรื่อง security ไหมครับ

**Comment by misterfocusth** [comment]
โอววว จริงด้วย ขอบคุณมากๆ ครับผม สงสัยผมรีบ Deploy ไปหน่อย 🤣 ยังไงเดียวจะรีบเเก้เลยครับผม ขอบคุณมากๆ ที่เเจ้งนะครับบบ 🙏
